name: Build and Push n8n Custom Image to GHCR

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  schedule:
    - cron: '0 0 * * *' # Trigger daily at midnight UTC (adjust as needed)
  workflow_dispatch: # Allows manual triggering from the GitHub Actions UI

jobs:
  build:
    runs-on: ubuntu-latest # Use a GitHub-hosted runner (Ubuntu)
    permissions:
      contents: read # Allow reading repository contents
      packages: write # Allow writing to GitHub Packages (GHCR)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to checkout your code

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Recommended for modern Docker builds (multi-platform, caching)

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io # Specify GHCR registry
          username: ${{ github.actor }} # Use the GitHub username that triggered the workflow
          password: ${{ secrets.GITHUB_TOKEN }} # Use the automatically provided GITHUB_TOKEN

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: . # Build context is the current directory (where your Dockerfile is)
          push: true # Push the image to the registry
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}
          cache-from: type=gha,scope=build-n8n-ghcr # Enable caching for faster builds
          cache-to: type=gha,mode=max,scope=build-n8n-ghcr
